[build]
  base = "/"
  publish = "build" # Make sure this points to the correct output directory
  command = "npm run build" # The command to build your site

[[redirects]]
  from = "/*"
  to = "/docs/:splat"
  status = 200
